#!/usr/bin/ansible-playbook
---
- hosts: tdoc1

  tasks:
    - name: deploy compose file
      copy:
        src: docker/visualizer/vis-compose.yml
        dest: ~/
        mode: 0644
    - name: Start the stack...
      shell: docker stack deploy -c ~/vis-compose.yml visualizer
