#!/usr/bin/ansible-playbook
---
- hosts: all,!master
  connection: local
  gather_facts: false
  
  vars:
    var_aws_region: eu-central-1


  tasks:
 
  - name: Get Instance IDs from aws
    ec2_instance_facts:
      region: "{{ var_aws_region }}"
      filters:
        "tag:Name": "{{ inventory_hostname }}"
        "instance-state-name": "running"
    delegate_to: localhost
    register: instance

  - name: debug
    debug:
      var: instance

  - name: Delete the selected EC2 instances
    ec2:
      region: "{{ var_aws_region }}"
      wait: no
      instance_ids: "{{ item.instance_id }}"
      state: absent
    delegate_to: localhost
    with_items: "{{ instance.instances }}"

