#!/usr/bin/ansible-playbook
---
- hosts: all
  connection: local
  gather_facts: no
  become: no 

  tasks:

  - name: find latest AMI for server
    ec2_ami_facts:
      owners: amazon
      region: eu-central-1
      filters:
        name: "amzn2-ami-hvm-2.0.*"
    register: amis
    delegate_to: localhost

  - name: now get the latest one
    set_fact:
      latest_ami: >
        {{ amis.images | sort(attribute='creation_date') | last }}
    delegate_to: localhost

  - name: Create an EC2 instance
    ec2:
      key_name: frank.kortstiege_aws_eu
      instance_type: t2.micro
      image: "{{ latest_ami.image_id }}"
      region: eu-central-1
      wait: no
      group: default
      count: 1
      vpc_subnet_id: subnet-a5a9f5d8
      assign_public_ip: yes
      instance_tags:
       Name: "{{ inventory_hostname }}" 
      state: present
    register: ec2
    delegate_to: localhost

- hosts: "{{ play_hosts }}"
  become: yes
  gather_facts: no

  tasks:
  - name: Add new instance to /etc/hosts
    lineinfile:
      path: /etc/hosts
      regexp: "{{ item.tags.Name }}$"
      line: " {{ item.private_ip }} {{ item.private_dns_name }} {{ item.tags.Name }}"
    with_items: "{{ ec2.instances }}"
    delegate_to: localhost

- hosts: "{{ play_hosts }}"
  remote_user: ec2-user
  become: yes
  gather_facts: no

  roles:
    - firststep
