
---
- name: Register kubernetes repo (Google)
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Register RHEL Extras Channel
  shell: "yum-config-manager --enable rhui-REGION-rhel-server-extras"

- name: Install docker
  package:
    name: docker
    state: present

- name: Add dockerroot group if not present
  group:
    name: dockerroot

- name: Enable Docker Deamon for group dockerroot
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: 0644

- name: Start/enable docker
  service:
    name: docker
    enabled: yes
    state: restarted

- name: Add kortstie to dockerroot group
  user:
    name: kortstie
    groups: dockerroot
    append: yes

- name: Install Python docker modules
  shell: "pip install docker"

- name: Install Kubernetes
  package:
    name: kubelet,kubeadm,kubectl
    state: present

- name: Start/enable kubernetes
  service:
    name: kubelet
    enabled: yes
    state: restarted



