
---
- name: Enable extras repo
  shell: "yum-config-manager --enable rhui-REGION-rhel-server-extras"

- name: Installiert docker
  package:
    name: docker,docker-compose,python2-pip
    state: present

#- name: Enable IPv4 Forwarding
#  lineinfile:
#   path: /usr/lib/sysctl.d/99-docker.conf
#   line: net.ipv4.ip_forward=1
#   state: present

- name: Add dockerroot group if not present
  group:
    name: dockerroot

- name: Enable Docker Deamon for group dockerroot
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: 0644

- name: Start/enable docker
  service:
    name: docker
    enabled: yes
    state: restarted

- name: Add kortstie to dockerroot group
  user:
    name: kortstie
    groups: dockerroot
    append: yes

- name: Install Python docker modules
  shell: "pip install docker"

