
version: "3"
services:
  web1:
    # replace username/repo:tag with your name and image details
    image: httpd
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    #volumes:
    #  - "/srv/dockershare/web1/:/usr/local/apache2/htdocs/"
    ports:
      - "8081:80"
    networks:
      - web1
networks:
  web1:

